services:
  nginx:
    build: srcs/nginx/
    image: nginx
    ports:
      - 443
    networks:
      - myNetwork
  wordpress:
    build: srcs/wordpress/
    image: wordpress
    ports: 
      - 9000:9000
    networks:
      - myNetwork
  mariadb:
    build: srcs/mariadb/
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - myNetwork

networks:
    myNetwork:


