services:
  nginx:
    build: 
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx
    ports:
      - 443
    networks:
      - myNetwork
  wordpress:
    build: srcs/wordpress/
    image: wordpress
    volumes: 
      - /home/calbor-p/data/wordpress:/var/www/html/
    ports: 
      - 9000:9000
    networks:
      - myNetwork
  mariadb:
    build: srcs/mariadb/
    image: mariadb
    volumes:
      - /home/calbor-p/data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    ports:
      - 3306:3306
    networks:
      - myNetwork

networks:
    myNetwork:


