  services:
    nginx:
      container_name: nginx
      build: 
        context: .
        dockerfile: ./requirements/nginx/Dockerfile
      ports:
        - 443:443
      volumes:
        - /home/calbor-p/data/wordpress:/var/www/html
        - /home/calbor-p/data/musicaltheory:/var/www/musicaltheory
      networks:
        - myNetwork
      depends_on:
      - wordpress
      restart: unless-stopped 
    wordpress:
      container_name: wordpress
      build: 
        context: .
        dockerfile: ./requirements/wordpress/Dockerfile
      volumes: 
        - /home/calbor-p/data/wordpress:/var/www/html
      ports: 
        - 9000:9000
      expose:
      - "9000"
      networks:
        - myNetwork
      depends_on:
        - mariadb
      restart: unless-stopped
    mariadb:
      container_name: mariadb
      build: 
        context: .
        dockerfile: ./requirements/mariadb/Dockerfile
      volumes:
        - /home/calbor-p/data/mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PWD}
      ports:
        - 3306:3306
      networks:
        - myNetwork
      env_file:
      - .env
      restart: unless-stopped

  networks:
      myNetwork:
        driver: bridge

 
