version: '2'
services:
  nginx:
    image: nginx
    ports: 443
    networks:
      - myNetwork
  wordpress:
    image: wordpress
    ports: 9000:9000
    networks:
      - myNetwork
  mariadb:
    image: mariadb
    ports: 3306:3306
    networks:
      - myNetwork


